model_checkpoint_last:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: 'data/models/${exp_name}'
  filename: 'last'
  auto_insert_metric_name: false
  save_top_k: 1
  save_on_train_epoch_end: true
  monitor: null
  every_n_epochs: 1
  save_last: true
  save_weights_only: false