model_checkpoint_best:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: 'data/models/${exp_name}'
  filename: 'best'
  auto_insert_metric_name: false
  save_top_k: 1
  monitor: 'val/loss'
  save_last: false
  save_weights_only: false