defaults:
  - hydra: default
  - trainer: default
  - callbacks:
      - learning_rate_monitor
      - model_checkpoint_best
      - model_checkpoint_last
      - model_checkpoint_step
      - rich
      - tqdm
  - logger: wandb
  - data: sqg
  - pre_pipeline: pre_normalize_q.yaml
  - post_pipeline: post_tendency_q.yaml
  - network: unet
  - train_module: flow_matching
  - _self_

exp_name: sqg_flow_matching_${now:%H-%M-%S}
logging_level: DEBUG
seed: 42
num_workers: 4
batch_size: 32

# To resume training from a checkpoint path
ckpt_path: null

# Set to true to enable torch.compile (may not be compatible with all models or hardware)
compile: false

# Overwrite network and pipeline configuration to use config groups
train_module:
  network: ${network}
  pre_pipeline: ${pre_pipeline}
  post_pipeline: ${post_pipeline}

# Set logger tags
logger:
  tags:
    - surrogate
    - train
    - flow-matching 
    - sqg
