# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    timeout_min: 60
    gpus_per_node: 8
    tasks_per_node: 8
    gres: "gpu:8"
    constraint: a100
    partition: gpu_p5
    cpus_per_task: 16
    qos: qos_gpu_a100-dev
    additional_parameters:
      account: ${oc.env:IDRPROJ}@a100
      distribution: "block:block"
      hint: nomultithread
      time: "00:30:00"
      mail-type: FAIL
      mail-user: chiara.zelco@ens.psl.eu
      signal: "SIGUSR1@120"
    setup:
      - "export WANDB_MODE=offline"
      - "export PATH='~/.local/bin':$PATH"
      - "set -x"
    stderr_to_stdout: true

logger:
  offline: true
  log_model: false
  mode: "offline"

num_workers: 8
batch_size: 4

trainer:
  accelerator: gpu
  precision: "bf16-mixed"
  devices: 8
  strategy: "ddp"

callbacks:
  tqdm_pbar:
    refresh_rate: 100
